### ISSUE TITLE
CLI?

### ISSUE THREAD

**Issue by crisdosaygo** [Tazeg/browserhistory#1]
This is great, but it would be awesome to have a command line version and output the data in a text format operated from the command line.

**Comment by Tazeg** [comment]
Thank you for your feedback.

A CLI and a GUI are 2 different things. This repo is aimed for a user friendly GUI, because end users are usually not developers.
I could make a pure CLI tool if needed but it won't be here.

I will add export features for example in CSV.

**Comment by crisdosaygo** [comment]
Thanks. I guess I can take a look at https://github.com/Tazeg/browserhistory/tree/main/electron/app/js if I want an idea of how you are getting the data. (*wow I didn't know chrome is storing in SQL*)
